org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false

# Fabric: https://fabricmc.net/versions.html
minecraft_version=1.16.5
yarn_mappings=1.16.5+build.10
loader_version=0.14.23

# Fabric API
fabric_version=0.42.0+1.16

# Мод
mod_version=1.0.0
maven_group=ru.blockoutline
archives_base_name=outline-1.16.5-fabric
